export default [
  {
    "login": "preetika-9",
    "id": 66292568,
    "node_id": "MDQ6VXNlcjY2MjkyNTY4",
    "avatar_url": "https://avatars.githubusercontent.com/u/66292568?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/preetika-9",
    "html_url": "https://github.com/preetika-9",
    "followers_url": "https://api.github.com/users/preetika-9/followers",
    "following_url": "https://api.github.com/users/preetika-9/following{/other_user}",
    "gists_url": "https://api.github.com/users/preetika-9/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/preetika-9/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/preetika-9/subscriptions",
    "organizations_url": "https://api.github.com/users/preetika-9/orgs",
    "repos_url": "https://api.github.com/users/preetika-9/repos",
    "events_url": "https://api.github.com/users/preetika-9/events{/privacy}",
    "received_events_url": "https://api.github.com/users/preetika-9/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Ush71",
    "id": 66295373,
    "node_id": "MDQ6VXNlcjY2Mjk1Mzcz",
    "avatar_url": "https://avatars.githubusercontent.com/u/66295373?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Ush71",
    "html_url": "https://github.com/Ush71",
    "followers_url": "https://api.github.com/users/Ush71/followers",
    "following_url": "https://api.github.com/users/Ush71/following{/other_user}",
    "gists_url": "https://api.github.com/users/Ush71/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Ush71/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Ush71/subscriptions",
    "organizations_url": "https://api.github.com/users/Ush71/orgs",
    "repos_url": "https://api.github.com/users/Ush71/repos",
    "events_url": "https://api.github.com/users/Ush71/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Ush71/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "itsmebrp",
    "id": 33576285,
    "node_id": "MDQ6VXNlcjMzNTc2Mjg1",
    "avatar_url": "https://avatars.githubusercontent.com/u/33576285?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/itsmebrp",
    "html_url": "https://github.com/itsmebrp",
    "followers_url": "https://api.github.com/users/itsmebrp/followers",
    "following_url": "https://api.github.com/users/itsmebrp/following{/other_user}",
    "gists_url": "https://api.github.com/users/itsmebrp/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/itsmebrp/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/itsmebrp/subscriptions",
    "organizations_url": "https://api.github.com/users/itsmebrp/orgs",
    "repos_url": "https://api.github.com/users/itsmebrp/repos",
    "events_url": "https://api.github.com/users/itsmebrp/events{/privacy}",
    "received_events_url": "https://api.github.com/users/itsmebrp/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "kiran22985",
    "id": 59924309,
    "node_id": "MDQ6VXNlcjU5OTI0MzA5",
    "avatar_url": "https://avatars.githubusercontent.com/u/59924309?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kiran22985",
    "html_url": "https://github.com/kiran22985",
    "followers_url": "https://api.github.com/users/kiran22985/followers",
    "following_url": "https://api.github.com/users/kiran22985/following{/other_user}",
    "gists_url": "https://api.github.com/users/kiran22985/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kiran22985/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kiran22985/subscriptions",
    "organizations_url": "https://api.github.com/users/kiran22985/orgs",
    "repos_url": "https://api.github.com/users/kiran22985/repos",
    "events_url": "https://api.github.com/users/kiran22985/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kiran22985/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Sabin08",
    "id": 18566657,
    "node_id": "MDQ6VXNlcjE4NTY2NjU3",
    "avatar_url": "https://avatars.githubusercontent.com/u/18566657?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Sabin08",
    "html_url": "https://github.com/Sabin08",
    "followers_url": "https://api.github.com/users/Sabin08/followers",
    "following_url": "https://api.github.com/users/Sabin08/following{/other_user}",
    "gists_url": "https://api.github.com/users/Sabin08/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Sabin08/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Sabin08/subscriptions",
    "organizations_url": "https://api.github.com/users/Sabin08/orgs",
    "repos_url": "https://api.github.com/users/Sabin08/repos",
    "events_url": "https://api.github.com/users/Sabin08/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Sabin08/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "luckymaharjan2000",
    "id": 73690402,
    "node_id": "MDQ6VXNlcjczNjkwNDAy",
    "avatar_url": "https://avatars.githubusercontent.com/u/73690402?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/luckymaharjan2000",
    "html_url": "https://github.com/luckymaharjan2000",
    "followers_url": "https://api.github.com/users/luckymaharjan2000/followers",
    "following_url": "https://api.github.com/users/luckymaharjan2000/following{/other_user}",
    "gists_url": "https://api.github.com/users/luckymaharjan2000/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/luckymaharjan2000/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/luckymaharjan2000/subscriptions",
    "organizations_url": "https://api.github.com/users/luckymaharjan2000/orgs",
    "repos_url": "https://api.github.com/users/luckymaharjan2000/repos",
    "events_url": "https://api.github.com/users/luckymaharjan2000/events{/privacy}",
    "received_events_url": "https://api.github.com/users/luckymaharjan2000/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Durga123-regmi",
    "id": 63439775,
    "node_id": "MDQ6VXNlcjYzNDM5Nzc1",
    "avatar_url": "https://avatars.githubusercontent.com/u/63439775?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Durga123-regmi",
    "html_url": "https://github.com/Durga123-regmi",
    "followers_url": "https://api.github.com/users/Durga123-regmi/followers",
    "following_url": "https://api.github.com/users/Durga123-regmi/following{/other_user}",
    "gists_url": "https://api.github.com/users/Durga123-regmi/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Durga123-regmi/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Durga123-regmi/subscriptions",
    "organizations_url": "https://api.github.com/users/Durga123-regmi/orgs",
    "repos_url": "https://api.github.com/users/Durga123-regmi/repos",
    "events_url": "https://api.github.com/users/Durga123-regmi/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Durga123-regmi/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "Sagarkathariya",
    "id": 58875185,
    "node_id": "MDQ6VXNlcjU4ODc1MTg1",
    "avatar_url": "https://avatars.githubusercontent.com/u/58875185?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/Sagarkathariya",
    "html_url": "https://github.com/Sagarkathariya",
    "followers_url": "https://api.github.com/users/Sagarkathariya/followers",
    "following_url": "https://api.github.com/users/Sagarkathariya/following{/other_user}",
    "gists_url": "https://api.github.com/users/Sagarkathariya/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/Sagarkathariya/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/Sagarkathariya/subscriptions",
    "organizations_url": "https://api.github.com/users/Sagarkathariya/orgs",
    "repos_url": "https://api.github.com/users/Sagarkathariya/repos",
    "events_url": "https://api.github.com/users/Sagarkathariya/events{/privacy}",
    "received_events_url": "https://api.github.com/users/Sagarkathariya/received_events",
    "type": "User",
    "site_admin": false
  }
]