export default {
  "login": "bipinparajuli",
  "id": 59670912,
  "node_id": "MDQ6VXNlcjU5NjcwOTEy",
  "avatar_url": "https://avatars.githubusercontent.com/u/59670912?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/bipinparajuli",
  "html_url": "https://github.com/bipinparajuli",
  "followers_url": "https://api.github.com/users/bipinparajuli/followers",
  "following_url": "https://api.github.com/users/bipinparajuli/following{/other_user}",
  "gists_url": "https://api.github.com/users/bipinparajuli/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/bipinparajuli/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/bipinparajuli/subscriptions",
  "organizations_url": "https://api.github.com/users/bipinparajuli/orgs",
  "repos_url": "https://api.github.com/users/bipinparajuli/repos",
  "events_url": "https://api.github.com/users/bipinparajuli/events{/privacy}",
  "received_events_url": "https://api.github.com/users/bipinparajuli/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Bipin Parajuli",
  "company": null,
  "blog": "https://bipinparajuli.netlify.app/",
  "location": "Thali, Kathmandu",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": "Bipin47267778",
  "public_repos": 42,
  "public_gists": 0,
  "followers": 8,
  "following": 5,
  "created_at": "2020-01-08T23:00:14Z",
  "updated_at": "2021-06-10T15:12:51Z"
}